# Generated by Django 3.0.3 on 2020-07-06 22:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200706_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 22, 19, 23, 44441, tzinfo=utc)),
        ),
    ]
